- pybaseball/playerid_lookup.py
Upon a call to playerid_lookup(), a DTypeWarning would appear stating
that Columns (8,9,10) had mixed types when reading the CSV file from
the Chadwick Register. Specified the types on those columns to suppress
the warning as well as lower memory footprint when reading the CSV
file.
Resolves: https://github.com/jldbc/pybaseball/issues/10
> Fix warning on playerid_lookup()

- pybaseball/team_results.py
- pybaseball/utils.py
This PR takes care of a couple of the to-do's in `team_results.py`. I've capitalized the team abbreviation and raised an error when season is greater than the current year.
I started to take work on raising an error when the season is before the team's first season and adding the capabilities to return results for every team, but I realized it was more complicated than I originally thought it would be. My original idea was to just include a dictionary that contained each team's abbreviation and their start year, but there are a ton of historical teams that can currently be found with `schedule_and_records` so that dictionary would need to be huge to cover everyone. I think it would be better to wait and see if there's a better way to handle it.
> Complete some schedule and results to-do's

- pybaseball/playerid_lookup.py
- pybaseball/statcast.py
Fixes the bug mentioned in #25. Also fixed up some formatting and long lines found via pylint and autopep8.
(closes #25)
> Drop old indexes when resetting index

- setup.py
With the addition of submodules, the `setup.py` needs to be updated so they will be installed with the package. This PR adds `find_packages` in the setup, excluding the `tests` dir. Closes https://github.com/jldbc/pybaseball/issues/109
> updates setup.py to find submodules

- .gitattributes
I'm seeing a noisy warning every time I use git on the command line, i.e. 
```
```
Presumable the # character isn't a valid comment delimiter in a `.gitattributes` file? This PR removes those comments.
> removes python style comment from gitattributes

- pybaseball/lahman.py
Different refactor for Lahman.
Keeping existing utility functions as-is, simplify the reuse, and add type annotations.
Fix the zipfile bug by just using `/` only, yes, it works just fine on Windows.
(Instead of #116)
> Alternate refactor for Lahman

- pybaseball/standings.py
- tests/integration/pybaseball/test_standings.py
This PR accomplishes two things:
1. Adds integration tests to the standings function, which was our code with the lowest coverage (only 11% under test).
2. While adding those integration tests, I discovered that due to an issue with BRef, all pre-1969 standings were erroring out.  As well I discovered that for 1981, we weren't accurately pulling the standings due to a quirk in BRef. So this fixes those issues as well.
So hooray for tests! They help us to catch bugs before our users do.
> Fix issues with standings bref api; add integration tests

- .github/workflows/pytest.yml
- tests/integration/pybaseball/test_league_pitching_stats.py
- tests/pybaseball/test_league_pitching_stats.py
This PR fixes a current broken unit test on master due to the fact that I forgot that `test_pitching_stats_bref_none` will pull current season's data, which of course changes every day 🤦 
So I turned it into a pure unit test. Which made me realize I'd put some unit tests in the integration test file, so I rectified that as well.
> Fix broken test; split out unit tests from integration tests

- .github/workflows/pytest.yml
- pybaseball/statcast.py
- setup.py
- tests/pybaseball/test_statcast.py
In this PR I've done a few things:
* Create a ProcessPoolExecutor to run statcast calls in parallel
* Change the statcast split to a single day, so that if the cache is enabled, each day is cached separately for ease of data reuse for overlapping calls
* Also I added a pytest plugin to parallelize the tests. They now run much faster.
The speed effects for this are pretty dramatic. For the following code:
```python
import timeit
timeit.timeit("data = statcast('2020-08-01', '2020-10-05')", "from pybaseball import statcast", number=1)
```
We've gone from @ 108 seconds to @ 26 seconds. So roughly **4x** faster.
Also the tests have gone from @ 350 seconds to @ 140 seconds, so @ **2.5x** faster.
So there are some downsides:
* The print statements within the workers seem to disappear. Not sure …
> Parallelize statcast calls

- pybaseball/plotting.py
- setup.py
This PR fixes the bug reported in #172 (closes #172). The issue was the `tooltips` argument in the function. Leaving it blank outside of a Jupyter notebook resulted in vega, what Altair uses to render images, throwing an error.
This fix works locally, but since there aren't any tests (and I'm not sure what the best way to test this would be) I'd appreciate other devs checking as well.
> Fix plotting bug

- pybaseball/playerid_lookup.py
- setup.py
- tests/integration/pybaseball/test_playerid_lookup.py
Substitutes Python standard lib `difflib` for GPL licensed `fuzzywuzzy`. Closes https://github.com/jldbc/pybaseball/pull/177
> Remove fuzzywuzzy

- pybaseball/league_pitching_stats.py
- pybaseball/utils.py
- tests/integration/pybaseball/test_league_batting_stats.py
- tests/integration/pybaseball/test_league_pitching_stats.py
Fixes bug in applying date range to `pitching_stats_range`. Closes https://github.com/jldbc/pybaseball/issues/188
> league pitching range fix

- CHANGELOG.md
- README.md
I noticed the README says the latest release is from last year, when it's really only from a few weeks ago. I don't want people second-guessing that this is an active repo.
> Fix typo in README and add latest release to the CHANGELOG

- tests/conftest.py
- tests/pybaseball/cache/test_cache.py
This attempts to stop the sporadic failures of the cache tests. It mocks the `safe_jsonify` method, which is called by the `save` method of a cache record. This prevents any files from being written during the cache testing. This will hopefully address the failures of `test_call_cache_ignores_expired`, `test_call_cache_gets_uncached_data`, `test_call_cache_load_fails_silently`.
Because there are now no files to load it also has to mock the json load method in the `test_call_cache_save_fails_silently` test.
> Cache tests updates

- docs/statcast_fielding.md
- docs/statcast_running.md
- pybaseball/statcast_fielding.py
- pybaseball/statcast_running.py
- pybaseball/utils.py
- tests/integration/pybaseball/test_statcast_fielding.py
- tests/integration/pybaseball/test_statcast_running.py
Pulling data from statcast's fielding and running leaderboards. Can change to fielder and runner if that makes more sense / is more consistent. Most of it was pretty straightforward except for `statcast_outs_above_average()` due to how the positions are handled - if there's a better way to do `norm_positions()`, I'm all ears. 
The [OAA leaderboard](https://baseballsavant.mlb.com/leaderboard/outs_above_average?type=Fielder&year=2020&team=&range=year&min=q&pos=of&roles=&viz=show) in particular has a lot of options and using `kwargs` so the user can supply more args might be a good next step after this.
There's also no catcher pop time data for 2020, which I found odd. Once all of this checks out I will start on the documentation and tests.
> Statcast Fielding & Running leaderboards

- docs/statcast.md
- pybaseball/statcast.py
Adds a `parallel` parameter to `pybaseball.statcast()`. If `False`, requests will be made sequentially rather than through a `ProcessPoolExecutor`.
The motivation for this is that I was trying to call the function in an AWS lambda function, where all multiprocessing is disabled. This might be a somewhat niche use case, so no worries if you don't want it. I didn't look into covering it in the tests, but I'm happy to.
> Make parallel statcast requests optional

- docs/statcast.md
I had some difficulty finding what each of the columns in the statcast data meant, and realized there isn't any link to the Baseball Savant page detailing exactly that.
Sorry for the extra changes. I forgot I have my editor remove trailing whitespace on saving.
> Link to baseball savant pitch-level docs

- docs/batting_stats.md
- docs/pitching_stats.md
Update description of the `qual` argument to reflect [actual behavior](https://github.com/jldbc/pybaseball/blob/bbd03a8b00bcd92e568f6907cacbe3c1ae51c0ee/pybaseball/datasources/fangraphs.py#L97). This came up because I noticed Bryce Harper is currently absent from batting stats unless you explicitly set the `qual` argument accordingly.
> Update description of `qual` argument in batting and pitching stats documentation

- pybaseball/league_batting_stats.py
- pybaseball/league_pitching_stats.py
Forces a utf-8 encoding for baseball reference data in `batting_stats_range` and `pitching_stats_range` before applying beautiful soup parsing. This should avoid confusion in the encoding due to inconsistency between the table and the footer of the page.
Closes https://github.com/jldbc/pybaseball/issues/218
> bugfix for truncated batting range data

- pybaseball/league_batting_stats.py
- pybaseball/league_pitching_stats.py
- tests/integration/pybaseball/test_league_batting_stats.py
- tests/integration/pybaseball/test_league_pitching_stats.py
Baseball-Reference player stat pages ([like this](https://www.baseball-reference.com/leagues/daily.fcgi?user_team=&bust_cache=&type=b&lastndays=7&dates=fromandto&fromandto=20190410.20190411&level=mlb&franch=&stat=&stat_value=0)) have player MLB IDs embedded in links. Scraping these IDs would be useful as `batting_stats_range` and `pitching_stats_range` return a Dataframe with Baseball-Reference player names as the only identifier but these are difficult to join on. This would grab the IDs from the links and add an `mlbID` column to the batting and pitching tables.
Example output of `pitching_stats_range`:
> Scrape MLB IDs from Baseball-Reference

- pybaseball/plotting.py
- tests/pybaseball/test_plotting.py
Multiplies the stadium coordinates by a factor 2.495 / 2.33 to put them on same scale as the `hc_x` and `hc_y` fields from mlbam. 
The scale factor was determined heuristically by:
- finding the scale of STADIUM_COORDS that will match the outfield dimensions, e.g., [for coors](https://www.seamheads.com/ballparks/ballpark.php?parkID=DEN02), 
- finding the scale for mlbam data so that hc_x, hc_y match the hit_distance_sc field
- the center (x=125, y=199) comes from [this hardball times article
](https://tht.fangraphs.com/research-notebook-new-format-for-statcast-data-export-at-baseball-savant/
)
> spraychart scales

- .gitignore
- pybaseball/statcast.py
- pybaseball/statcast_pitcher_spin.py
Fixes #229 by converting out ProcessPoolExecutor to a ThreadPoolExecutor. ProcessPoolExecutor is a little more picky about where it runs.
As well I was getting a TypeError in `statcast_pitcher_spin.py` when running the tests (python 3.7.9):
```
pybaseball/statcast_pitcher_spin.py:135: in find_phi
df['phi'] = df['phi'].round(0).astype('int64')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = 0       190.754943
1       300.794706
2        243.13629
3        288.17292
4       291.559998
...    
4215...5478
4216    448.531754
4217    436.495487
4218    440.636358
4219    434.056495
Name: phi, Length: 4220, dtype: object
decimals = 0, args = (), kwargs = {}
def round(self, decimals=0, …
```
> Change statcast pool from process to thread; fix TypeError

- .github/workflows/pytest.yml
Testing out a matrix that will test changes against all current python versions.
@schorrm I think this could help catch things like what I found in #231 which was a TypeError that seems to happen in 3.7+, but not previously caught in our 3.6 tests (which you can see are causing failures below in 3.7 and 3.8).
As well we may be able to easily add 3.10 when that's ready to see how our code base will fair.
> Add a matrix to test on all python versions

- pybaseball/team_results.py
Issue #242 notes that drop now throws a `FutureWarning` for non-keyword args beyond labels. Adding the `axis` keyword so this warning doesn't persist.
> Add axis keyword to df.drop call

- README.md
Addresses the recurring `BrokenProcessPool` error first raised in #211
> Add troubleshooting to readme

- pybaseball/__init__.py
- pybaseball/lahman.py
This PR updates `pybaseball.__init__.py` and `pybaseball.lahman.py` to comply with changes made to the recent release of the Lahman/Baseball-Databank database.
> Update lahman for changes to directory structure

- pybaseball/lahman.py
#251 introduced a bug in `__init__.py` after updating `teams()` to `teams_core()`. This updates the call to the new `teams_core()`.
before:
```
In [1]: from pybaseball.batting_stats_range import batting_stats_range
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from pybaseball.league_batting_stats import batting_stats_range
File ~/Documents/github/pybaseball/pybaseball/__init__.py:79, in <module>
77 from .lahman import schools
78 from .lahman import series_post
---> 79 from .lahman import teams_core
80 from .lahman import teams_upstream
81 from .lahman import teams_franchises
ImportError: cannot import name 'teams_core' from 'pybaseball.lahman' …
```
> Rename teams to teams_core

- pybaseball/split_stats.py
The list fv was declared in a for loop such that the dictionary creation couldn't access it. This caused an error, "local variable 'fv' referenced before assignment" when calling get_splits() with player_info=True.
> Fixed issue in get_player_info()

- pybaseball/league_batting_stats.py
#257 highlighted that there's no IDs returned via `batting_stats_range`. The scraping currently returns the MLB AM ID, we just drop it in the conversion to numerics. This PR adds it back in.
New output:
```
In [1]: from pybaseball.league_batting_stats import batting_stats_range
In [2]: batting_stats_range("2022-04-10", end_dt="2022-04-11").head()
Out[2]:
Name  Age  #days     Lev           Tm  G  PA  AB  R  H  2B  3B  HR  RBI  BB  IBB  SO  HBP  SH  SF  GDP  SB  CS     BA    OBP    SLG    OPS   mlbID
1        C.J. Abrams   21     12  Maj-NL    San Diego  1   1   1  0  0   0   0   0    0   0    0   0    0   0   0    0   0   0  0.000  0.000  0.000  0.000  682928
2  Jos\xc3\xa9 Abreu   35     12  Maj-AL      Chicago  1   5   4  3  2   1   0   0    2   1    0   0    0   0   0    0   0   0 …
```
> Add mlbID to return table of batting_stats_range

- .github/workflows/pytest.yml
- Makefile
- pybaseball/cache/func_utils.py
- pybaseball/datasources/fangraphs.py
- scripts/validate_cache.py
This adds a CI stage to illustrate the problem mentioned here https://github.com/jldbc/pybaseball/issues/267 https://github.com/jldbc/pybaseball/issues/221
namely that when the cache is enabled, the call to get the fangraphs batting and pitching stats return the same dataframe.
> Use objects qualified name in caching 

- pybaseball/statcast_batter.py
- pybaseball/statcast_fielding.py
- pybaseball/statcast_pitcher.py
- pybaseball/statcast_running.py
- pybaseball/utils.py
- tests/integration/pybaseball/test_statcast_batter.py
- tests/integration/pybaseball/test_statcast_pitcher.py
This addresses #279, in which there's a whitespace in `first_name`. The issue was flagged for `statcast_batter_exitvelo_barrels`, however it permeated to most the statcast calls. I implemented an effectively one-line solution in utils that strips any whitespace from the column names of the statcast calls, and imported the new function and used where needed.
> Sanitize whitespace in column names from statcast calls

- pybaseball/team_results.py
- tests/integration/pybaseball/test_amateur_draft.py
One line change, addressing the FutureWarning raised in #270
> Use columns keyword rather than no-keyword axis for drop in team_results

- docs/statcast_fielding.md
- pybaseball/statcast_fielding.py
- tests/integration/pybaseball/test_statcast_fielding.py
Proposed feature which simply adds an argument to the "pitcher_fielding" statcast pull in order to allow for "view" changes (options are: Fielder, Fielding Team, Batting, Batting Team, Pitcher). Helpful for pulling OOA and RAA for defense behind a particular pitcher and retrieving team fielding information. Set default to previous hardcode "Fielder"
> Feat: Update "OOA Behind Pitcher" function

- .github/workflows/pytest.yml
- README.md
Since we have dropped Python 3.6 support on the PyBaseball project - I'm dropping the 3.6 version of Python from the python-version on the test jobs strategy.
> Dropping Python 3.6 from python-versions

- pybaseball/playerid_lookup.py
Updates the reading of the chadwick register from read people files from the [chadwickbureau](https://github.com/chadwickbureau/register). The register has changed file format from one file containing all people, to several files, e.g. `people-0.csv`. 
This PR updates code to 
* load the zip archive of `chadwickbureau/register`
* search the zip archive for `people*.csv`
* instead of assuming path `people.csv` 
* read them all into a dataframe
closes https://github.com/jldbc/pybaseball/issues/308
> update chadwick register access

- pybaseball/league_batting_stats.py
- pybaseball/league_pitching_stats.py
- tests/pybaseball/test_league_batting_stats.py
- tests/pybaseball/test_league_pitching_stats.py
While introducing/familiarizing myself with this repo I noticed a few places where the assumed end of season was no later than November 1st. We've had a few World Series in recent memory end a few days after the 1st. I figured adjusting this to end of month would be a good first issue opportunity.
> Change assumed end of season date from November 1 to November 30

- docs/batting_stats.md
- docs/fangraphs.md
- docs/pitching_stats.md
- docs/team_batting.md
- docs/team_fielding.md
- docs/team_pitching.md
- pybaseball/enums/fangraphs/league.py
Now that [Fangraphs supports negro leagues](https://blogs.fangraphs.com/negro-leagues-data-is-now-available-on-fangraphs/), we should be able to pull that data through pybaseball. New values need to be added to the `FangraphsLeague` enum otherwise an exception is thrown.
> Add Negro Leagues To `FangraphsLeague`

- pybaseball/league_batting_stats.py
- pybaseball/league_pitching_stats.py
The issue is that we are wrongly encoding a bytes object parsed to a string
what we need to do instead is, decode the bytes object directly. 
This commit changes that, to decoding the content directly from _**bytes**_ into utf-8
See, the results after these changes: 
https://github.com/jldbc/pybaseball/issues/393#issuecomment-1836852467
> ISSUE 393 : Decoding the content into utf-8 to avoid encoding issues 

- pybaseball/retrosheet.py
Gradually updating retrosheet.py to work with the new organization of Chadwick Bureau's retrosheet repo. As described in the issue (#414), all functions return errors or just simply do not work. This should also eventually resolve #392 & #407.
Initial commits fix the events and season_game_logs functions.
> Updating retrosheet.py to work with new chadwickbureau/retrosheet repo

- pybaseball/__init__.py
- pybaseball/statcast_batter.py
- pybaseball/statcast_fielding.py
- pybaseball/statcast_pitcher.py
- tests/integration/pybaseball/test_statcast_batter.py
- tests/integration/pybaseball/test_statcast_fielding.py
- tests/integration/pybaseball/test_statcast_pitcher.py
I added the ability to get bat tracking leaderboards for batters and pitchers. I also fixed the OAA link as the old link was no longer working.
> Added bat tracking and fixed Outs Above Average Leaderboard link

- pybaseball/cache/cache.py
The cache writer has been writing corrupted files. The reason seems to be that statcast takes dates as args and these can't be json serialized, example,
```
>>> import json
>>> import datetime
>>> json.dumps(datetime.date.today())
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.12/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 200, in encode
chunks = self.iterencode(o, _one_shot=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 258, in iterencode
return _iterencode(o, 0)
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 180, in default
raise TypeError(f'Object of type …
```
> cache serializing error

- pybaseball/top_prospects.py
Passes `UserAgent` in the header for `top_prospects` in order to render the javascript table. Example, https://stackoverflow.com/questions/27652543/how-can-i-use-pythons-requests-to-fake-a-browser-visit-a-k-a-and-generate-user
Closes https://github.com/jldbc/pybaseball/issues/446
> render js table

- pybaseball/datasources/bref.py
- setup.py
usese the curl_cffi requests instead of requests.
This will help avoid cloudflare checks on requests, and impersonates the chrome request methods. 
This fixes issue 470
> fix issue 470, using curl_cffi requests library instead of requests

- pybaseball/__init__.py
- pybaseball/cache/cache.py
- pybaseball/statcast_batter.py
- pybaseball/statcast_fielding.py
- pybaseball/statcast_pitcher.py
- tests/conftest.py
- tests/integration/pybaseball/test_statcast_batter.py
- tests/integration/pybaseball/test_statcast_fielding.py
- tests/integration/pybaseball/test_statcast_pitcher.py
This PR adds Statcast's Attack Zone tool to PyBaseball. 
Run Values are a sabermetric tool used to measure offensive production. In 2019, the Baseball Savant added the ability to measure Run Values in a pre-defined "Attack Zone"
Run Values/Attack Zone Documentation: https://tangotiger.com/index.php/site/article/statcast-lab-swing-take-and-a-primer-on-run-value
In 2025, Atlanta Braves shortstop Ozzie Albies tallied -29 Runs in the Shadow Zone, last in the Majors   
-----------------------------------
1. Added function _statcast_pitcher_run_value_ in _statcast_pitcher_ file 
- Added try/except/finally clause designed to return HTTP Error if website cannot be reached
- Created Tests in _test_statcast_pitcher_ to test function
2. Added function _statcast_batter_run_value_ in _statcast_batter_ …
> Added Statcast Run Value, Fixed Statcast Filtering, & Updated Tests
