jldbc/pybaseball

pybaseball/league_batting_stats.py
probably not the most elegant solution but it works.  lines 74-77 are where the year is checked. Rest of changes are just trying to get rid of linter/PEP8 errors
=> add error message for pre-2008 requests

pybaseball/__init__.py, pybaseball/statcast.py
* New statcast_single_game() method takes MLB game ID and returns statcast data for that game
=> Add method for getting Statcast data for a single game.

pybaseball/standings.py
Added ability to pull standings up to 1903 instead of up to 1969. Working on extending ability all the way to 1871.
=> Extend capability of standings.py

pybaseball/statcast.py
Cool library! Messing with the stat cast data I came across a bug that should be fixed with this PR
=> Added 'pitch_name' to not_numeric list

pybaseball/__init__.py, pybaseball/statcast_batter.py, pybaseball/statcast_pitcher.py, pybaseball/utils.py
This PR is an implementation of the solution to issue #20 I proposed in issue #22. So far I've only implemented this change in `statcast_batter` and `statcast_pitcher`, I haven't tried anything with the rest of the `statcast` functions. I created a new `utils.py` file to avoid some code duplication.
I've run `statcast_batter` and `statcast_pitcher` a few times and everything seems to work as it should. Labeled WIP because I want to play with the other `statcast` functions to see if they have any of the same request timeout errors before saying it's ready for a full review.
=> Split Statcast Queries

docs/retrosheet.md, pybaseball/__init__.py, pybaseball/retrosheet.py, pybaseball/utils.py
This PR adds some functions to pull game logs from Retrosheet. I included some documentation and the notice required by Retrosheet to use their data. I ran all of the functions and everything seemed to work as expected. Let me know if there's anything else I need to do/add.
=> Add Retrosheet functions

docs/batting_stats.md, docs/batting_stats_bref.md, docs/batting_stats_range.md, docs/bwar_bat.md, docs/bwar_pitch.md, docs/lahman.md, docs/pitching_stats.md, docs/pitching_stats_bref.md, docs/pitching_stats_range.md, docs/playerid_lookup.md, docs/playerid_reverse_lookup.md, docs/schedule_and_record.md, docs/standings.md, docs/statcast.md, docs/statcast_batter.md, docs/statcast_pitcher.md, docs/statcast_single_game.md, docs/team_batting.md, docs/team_pitching.md
Python code blocks in markdown will now be colorized.
=> Added syntax highlighting to docs

docs/lahman.md, pybaseball/__init__.py, pybaseball/lahman.py
Several things. Almost same code as previous PR, just without the previous garbage, and with the following additional changes:
1. I used the Chadwick Databank URL on GitHub, it's better hosting, I think, and also stays up to date.
2. In the newest one, with stats from 2018, they renamed `Master.csv` to `People.csv`. I accounted for the new filename in the code, added a `people()` function to preserve the symmetry, though I left in `master` as an alias to `people` to preserve backwards compatibility.
=> Revised Lahman fixes

pybaseball/batting_leaders.py, pybaseball/pitching_leaders.py
Scraper started breaking for me a couple days ago so I fixed it, ran into some pandas type errors so I added some type checking as well. For some reason my local copy used html.parser instead of lxml so I changed that, too.
=> Fixed broken scraper target and added typechecking

setup.py
Small update for the pypi push fixing fangraphs bug in 1.0.8
=> Version bump 1.0.8

docs/team_fielding.md, docs/team_fielding_bref.md, pybaseball/__init__.py, pybaseball/team_fielding.py
This PR will support the fielding data from FanGraphs and Baseball Reference in a similar way to the pitching and batting data.
=> Add support for fielding data

pybaseball/statcast.py, tests/pybaseball/test_statcast.py
=> Fix statcast team support

setup.py, tests/conftest.py, tests/integration/pybaseball/datasources/test_fangraphs.py, tests/pybaseball/datasources/test_fangraphs.py
Going to slowly add some integration tests to the project. Here's the first of more to come.
This covers the fg_batting_data function. Per @schorrm 's request, this only brings back a page of 10 when possible so as to keep these lightweight and faster.
I tried to be expansive in terms of testing all possible parameters.
Also I added code coverage to the unit test runner so we'll have a good idea of where we need to shore up our tests.
=> Integration tests for fg_batting_data

tests/integration/pybaseball/test_team_results.py
Evidently the new Schedule and Record column is only available SOMETIMES. 🙄
=> BRef is giving me whiplash

pybaseball/league_batting_stats.py, pybaseball/league_pitching_stats.py, pybaseball/statcast.py, pybaseball/utils.py, tests/integration/pybaseball/test_league_batting_stats.py, tests/integration/pybaseball/test_league_pitching_stats.py, tests/pybaseball/test_league_batting_stats.py, tests/pybaseball/test_league_pitching_stats.py, tests/pybaseball/test_statcast.py, tests/pybaseball/test_utils.py
In this PR:
- Refactored the various sanitize and validate date functions strewn across the code into one cohesive function
- Add tests for league_batting_stats
- Rearranged some tests that were incorrectly categorized (unit vs. integration)
=> Refactor common code; Add tests for league batting stats

README.md, pybaseball/statcast.py, setup.py
Roll back the entire statcast file to fix the perf issues in #154
=> Statcast Hotfix

.github/workflows/pytest.yml, scripts/statcast_timing.py
This PR adds a step to the CI that will execute a large query against statcast and check that it completes within a given time threshold. This will help make sure subsequent PRs are taking care of https://github.com/jldbc/pybaseball/issues/154
=> statcast large-query timing script in CI

pybaseball/datahelpers/postprocessing.py, pybaseball/datasources/statcast.py, pybaseball/statcast.py, tests/integration/pybaseball/test_statcast.py, tests/pybaseball/conftest.py, tests/pybaseball/datahelpers/test_postprocessing.py, tests/pybaseball/datasources/test_fangraphs.py, tests/pybaseball/datasources/test_html_table.py, tests/pybaseball/test_amateur_draft.py, tests/pybaseball/test_batting_leaders.py, tests/pybaseball/test_pitching_leaders.py, tests/pybaseball/test_statcast.py, tests/pybaseball/test_team_batting.py, tests/pybaseball/test_team_fielding.py, tests/pybaseball/test_team_pitching.py
=> Change how we postprocess statcast to improve performance

pybaseball/playerid_lookup.py
This PR resolves a bug in the new spell check changes for playerid_lookup that isn't handling names that are abbreviated or three word names like JD Martinez, Hyun Jin Ryu, or Tommy La Stella.
=> Spell Check bug fix for 3 word names

pybaseball/teamid_lookup.py
=> get a logger instead of globally config logging

tests/integration/pybaseball/test_league_batting_stats.py
This adds a test for the issue mentioned in https://github.com/jldbc/pybaseball/issues/218
=> bref parsing test

pybaseball/team_game_logs.py, tests/integration/pybaseball/test_team_game_logs.py
=> Fix logic for determining if team is Home or Away for team game logs

.gitignore, docs/statcast_fielding.md, pybaseball/__init__.py, pybaseball/statcast_fielding.py, tests/integration/pybaseball/test_statcast_fielding.py
Introduces function to retrieve new Baseball Savant feature Fielding Run Values. It's a compilation of OAA and other arm tracking / framing stats into one main defensive metric, really interesting new work actually and I figured it could be useful in pybaseball.
This is my first ever pull request and contribution to a public open source project, so go easy on me! I expect to have gotten a few things wrong but I have read the contributing guidelines and aimed to follow them, but please make any desired changes.
Thanks!
=> Added Fielding Run Value (FRV)

pybaseball/playerid_lookup.py, tests/integration/pybaseball/test_playerid_lookup.py
I ran into a problem while using this package. I wanted to be strict in my player search, but a lot of my searches were failing due to accented letters. This PR addresses this issue by allowing you to search for exact names while ignoring accented letters
=> added ignore_accents option

pybaseball/retrosheet.py, pybaseball/teamid_lookup.py, tests/pybaseball/test_teamid_lookup.py
- Rewrite the retrosheet fix with if/elif to avoid requiring 3.10
- Fix team ID lookup stuff etc
=> fix teamid lookup warning stuff
